app1/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^page1/$', views.page1, name='page1'),
    url(r'^page2/$', views.page2, name='page2'),
]

comments/urls.py
from django.conf.urls import url

from . import views
app_name = 'comments'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add_comment/$', views.add_comment, name='add_comment'),
    url(r'^add_comment/add/$', views.add_comment_form, name='add_comment_form'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<comment_id>[0-9]+)/delete/$', views.del_comment_form, name='del_comment_form'),
    url(r'^(?P<comment_id>[0-9]+)/confirm/$', views.confirm_comment_form, name='confirm_comment_form'),
    url(r'^(?P<pk>[0-9]+)/edit/$', views.EditCommentView.as_view(), name='edit_comment'),
    url(r'^(?P<comment_id>[0-9]+)/edit/edit$', views.edit_comment_form, name='edit_comment_form'),
]

test1/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^comments/', include('comments.urls')),
    url(r'^polls/', include('polls.urls')),
    url(r'^app1/', include('app1.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$', views.LoginFormView.as_view(), name='login'),
    url(r'^accounts/logout/$', views.LogoutView.as_view(), name='logout'),
#   url(r'^polls/page1/', include('polls.urls')),
#   url(r'^polls/test/', include('polls.urls')),
#   url(r'^app1/page1/', include('app1.urls')),
#   url(r'^app1/page2/', include('app1.urls')),	
]

comments/models.py
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone



class Comment(models.Model):
    comment_name = models.CharField('Username', max_length = 200)
    comment_email = models.CharField('Email', max_length = 200)
    comment_text = models.CharField('Text', max_length = 200)
    pub_date = models.DateTimeField('Date published')
	# If True comment enabled
    enabled = models.BooleanField('Enabled', default = False)
    user_id = models.IntegerField('User ID', default = 0)
    def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        out = 'Name: ' + self.comment_name + ' || Email: ' + self.comment_email
        return out

comments/views.py
#from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, Http404, render
from django.core.urlresolvers import reverse, reverse_lazy
from django.contrib.auth.models import Permission, User
from django.utils import timezone
from django.views import generic

from django.views.generic.edit import FormView
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from django.views.generic.base import View

from .models import Comment

#def index (request):
#    latest_comment_list = Comment.objects.order_by('-pub_date')
#    context = {'latest_comment_list': latest_comment_list}
#    return render(request, 'comments/index.html', context)

class IndexView(generic.ListView):
    template_name = 'comments/index.html'
    context_object_name = 'latest_comment_list'

    def get_queryset(self):
        return Comment.objects.order_by('-pub_date')

########## OLD
#    latest_comment_list = Comment.objects.order_by('-pub_date')[:5]
#    template = loader.get_template('comments/index.html')
#    context = RequestContext(request, {
#        'latest_comment_list': latest_comment_list,
#    })
#    return HttpResponse(template.render(context))

#    latest_comment_list = Comment.objects.order_by('-pub_date')[:5]
#    output = ', '.join([q.comment_text for q in latest_comment_list])
#   return HttpResponse(output)
##########

#def detail (request, comment_id):
#    comment = get_object_or_404(Comment, pk = comment_id)
#    return render(request, 'comments/detail.html', {'comment': comment})

class DetailView(generic.DetailView):
    model = Comment
    template_name = 'comments/detail.html'

def add_comment(request):
    return render(request, 'comments/add_comment.html')

def add_comment_form(request):
    try:
        userId = 0
        if request.user.is_authenticated():
            userId = request.user.id
        add = Comment(comment_name = request.POST['name'], 
                      comment_email = request.POST['email'],
                      comment_text = request.POST['comment'],
                      pub_date = timezone.now(),
                      user_id = userId
        )
        add.save()
    except (KeyError, Comment.DoesNotExist):
        #return HttpResponseRedirect(reverse('comments:index'))
        raise Http404('Not found')
    else:
        return HttpResponseRedirect(reverse('comments:index'))

def del_comment_form(request, comment_id):
    try:
        # Check auth
        comment = Comment.objects.get(pk = comment_id)
        if request.user.has_perm('comments.delete_comment') or comment.user_id == request.user.id:
            comment.delete()
    except (KeyError, Comment.DoesNotExist):
        # Not work
        raise Http404('Not found')
    else:
        return HttpResponseRedirect(reverse('comments:index'))

def confirm_comment_form(request, comment_id):
    try:
        # Check auth
        comment = Comment.objects.get(pk = comment_id)
        if request.user.has_perm('comments.change_comment'):
            if comment.enabled == True:
                comment.enabled = False
            else:
                comment.enabled = True
            comment.save()
            return HttpResponseRedirect(reverse('comments:detail', args=(comment_id,)))
    except (KeyError, Comment.DoesNotExist):
        # Not work
        raise Http404('Not found')
    else:
        return HttpResponseRedirect(reverse('comments:index'))

#def edit_comment(request, comment_id):
#   return render(request, 'comments/edit_comment.html')
class EditCommentView(generic.DetailView):
    model = Comment
    template_name = 'comments/edit_comment.html'

def edit_comment_form(request, comment_id):
    try:
        comment = Comment.objects.get(pk = comment_id)
        if request.user.has_perm('comments.change_comment') or comment.user_id == request.user.id:
            comment.comment_text = request.POST['comment']
            comment.save()
        return HttpResponseRedirect(reverse('comments:detail', args=(comment_id,)))
    except (KeyError, Comment.DoesNotExist):
        raise Http404('Not found')
    else:
        return HttpResponseRedirect(reverse('comments:index'))

comments/templates/comments/add_comment.html
{% extends 'base.html' %}

{% block title %}Add comment{% endblock %}

{% block content %}
    <h2>Add comment</h2>

    {% if user.is_authenticated and perms.comments.add_comment %}
        {% if error_message %}
            <div class="alert alert-danger">
                <strong>{{ error_message }}</strong>
            </div>
        {% endif %}

        <form action="{% url 'comments:add_comment_form' %}" method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <label for="userName">Name</label>
                <input type="text" name="name" class="form-control" id="userName" placeholder="Name"
                {% if user.username %}value="{{ user.username }}" readonly{% endif %}
                required>
            </fieldset>
            <fieldset class="form-group">
                <label for="userEmail">Email</label>
                <input type="email" name="email" class="form-control" id="userEmail" placeholder="Email"
                {% if user.email %}value="{{ user.email }}" readonly{% endif %}
                required>
            </fieldset>
            <fieldset class="form-group">
                <label for="userComment">Comment</label>
                <textarea name="comment" class="form-control" id="userComment" rows="3" required></textarea>
            </fieldset>
            <button type="submit" class="btn btn-primary" value="Add">Add comment</button>
        </form>
    {% else %}
        <div class="alert alert-info">
            You are not permissions for Add comments
        </div>
    {% endif %}

    <div class="btn-back">
        <a class="btn btn-xs btn-default" href="{% url 'comments:index' %}">Go back</a>
    </div>
{% endblock %} 

comments/templates/comments/detail.html
{% extends 'base.html' %}

{% block title %}Comment detail{% endblock %}

{% block content %}

    {% if perms.comments.change_comment or comment.enabled or user.id == comment.user_id %}
        <p>
            <strong>Name</strong>
            <br>
            {{ comment.comment_name}}
        </p>
        <p>
            <strong>Email</strong>
            <br>{{ comment.comment_email}}
        </p>
        <p>
            <strong>Date</strong>
            <br>
            {{ comment.pub_date|date:"d.m.Y H:i:s"}}
        </p>
        <p>
            <strong>Comment</strong>
            <br>
            {{ comment.comment_text}}
        </p>
    {% else %}
        <div class="alert alert-danger">
            <strong>This comment not moderated</strong>
        </div>
    {% endif %}

    {% if perms.comments.change_comment %}
        <p>
            <a href="{% url 'comments:confirm_comment_form' comment.id %}" class="btn btn-sm 
                {% if comment.enabled %}btn-success">Comment enabled{% else %}btn-danger">Comment disabled{% endif%}
            </a>
        </p>
    {% endif %}

    {% if perms.comments.change_comment or user.id == comment.user_id %}
        <p>
            <a class="btn btn-sm btn-default" href="{% url 'comments:edit_comment' comment.id %}">Edit comment</a>
        </p>
    {% endif %}

    {% if perms.comments.delete_comment or user.id == comment.user_id %}
        <p>
            <a onclick="return Confirmation();" class="btn btn-default" href="{% url 'comments:del_comment_form' comment.id %}">Delete comment</a>
        </p>
    {% endif %}


    <div class="btn-back">
        <a class="btn btn-xs btn-default" href="{% url 'comments:index' %}">Go back</a>
    </div>
{% endblock %} 

comments/templates/comments/edit_comment.html
{% extends 'base.html' %}

{% block title %}Edit comment{% endblock %}

{% block content %}
    <h2>Edit comment</h2>

    {% if perms.comments.change_comment or user.id == comment.user_id %}
        {% if error_message %}
            <div class="alert alert-danger">
                <strong>{{ error_message }}</strong>
            </div>
        {% endif %}

        <form action="{% url 'comments:edit_comment_form' comment.id %}" method="post">
            {% csrf_token %}
            <p>
                <strong>Name</strong>
                <br>
                {{ comment.comment_name }}
            </p>
            <p>
                <strong>Email</strong>
                <br>
                {% if comment.comment_email %}
                    {{ comment.comment_email }}
                {% else %}
                    not found
                {% endif %}
            </p>
            <fieldset class="form-group">
                <label for="userComment">Comment</label>
                <textarea name="comment" class="form-control" id="userComment" rows="3" required>{{ comment.comment_text }}</textarea>
            </fieldset>
            <button type="submit" class="btn btn-primary" value="Edit">Save</button>
        </form>
    {% else %}
        <div class="alert alert-info">
            You are not permissions for Edit comments
        </div>
    {% endif %}

    <div class="btn-back">
        <a class="btn btn-xs btn-default" href="{% url 'comments:index' %}">Go back</a>
    </div>
{% endblock %} 

comments/templates/comments/index.html
{% extends 'base.html' %}

{% block title %}Comments{% endblock %}

{% block content %}
 
    {% if perms.comments.add_comment %}
        <a class="btn btn-primary" href="{% url 'comments:add_comment'%}">Add comment</a>
    {% else %}
        <div class="alert alert-danger">
            <strong>You are not permissions for Add comments</strong>
        </div>
    {% endif %}


    {% if latest_comment_list %}
        <div class="table-block">
            <table class="table table-bordered table-striped table-hover table-responsive">
                <tbody>
            {% for comment in latest_comment_list %}
                {% if comment.enabled or perms.comments.change_comment or user.id == comment.user_id %}
                    <tr>
                        <td>
                            <a href="{% url 'comments:detail' comment.id %}">{{ comment.comment_name }}</a>
                        </td>
                        <td>{{ comment.pub_date|date:"d.m.Y H:i:s"}}</td>
                    </tr>
	            {% endif %}
            {% endfor %}
                </tbody> 
            </table>
        </div>
    {% else %}
        <div class="alert alert-info">
            <strong>No comments are available</strong>
        </div>
    {% endif %}
{% endblock %}